# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту usalekse@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -usalekse@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always

# Ключ доступа к сервису codecov.io
env:
  global:
    - CODECOV_TOKEN="430fe897-58da-4c3e-85d3-a04477ea3b5e"